apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-persons-grpc
  name: udaconnect-persons-grpc
  namespace: udaconnect
spec:
  ports:
  - name: "30003"
    port: 30003
    targetPort: 5000
  selector:
    service: udaconnect-persons-grpc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-persons-grpc
  name: udaconnect-persons-grpc
  namespace: udaconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-persons-grpc
  template:
    metadata:
      labels:
        service: udaconnect-persons-grpc
    spec:
      containers:
      - image: dpoulopoulos/udaconnect-persons-grpc:v0.1.0
        name: udaconnect-persons-grpc
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
