---
openapi: 3.0.0
info:
  title: Persons Endpoint
  description: Persons API for project Udaconnect
  version: 1.0.0
paths:
  /api/persons:
    get:
      summary: Gets every Person
      description: |
        Retrieves all Persons stored in the database
      operationId: getPersons
      responses:
        "200":
          description: Successfully retrieved all Persons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
        "400":
          description: Bad input parameter
    post:
      summary: Creates a new Person record in the database
      description: |
        Create a new person record in the database with specific attributes
      operationId: createPerson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonId'
      responses:
        "200":
          description: Successfully created a new Person
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        "400":
          description: Bad input parameter
  /api/persons/{personId}/connection:
    get:
      summary: Gets the connections of a specific Person
      description: |
        Retrieves all connections for a specific Person
      operationId: getConnections
      parameters:
      - in: query
        description: Proximity to a given user in meters
        name: distance
        required: True
        schema:
          type: string
      - in: query
        description: End date range
        name: endDate
        required: True
        schema:
          type: string
      - in: query
        description: Start date range
        name: startDate
        required: True
        schema:
          type: string
      - name: personId
        in: path
        description: The Person's ID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Successfully retrieved all connections for a Person
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Connection'
        "400":
          description: Bad input parameter
components:
  schemas:
    Person:
      required:
      - company_name
      - first_name
      - id
      - last_name
      type: object
      properties:
        id:
          type: integer
          example: 1
        first_name:
          type: string
          example: Dimitris
        last_name:
          type: string
          example: Poulopoulos
        company_name:
          type: string
          example: Dimpo
    PersonId:
      required:
      - company_name
      - first_name
      - last_name
      type: object
      properties:
        first_name:
          type: string
          example: Dimitris
        last_name:
          type: string
          example: Poulopoulos
        company_name:
          type: string
          example: Dimpo
    Connection:
      required:
      - person
      - location
      type: object
      properties:
        person:
          type: object
          example: {"id": "1",
                    "first_name": "Dimitris",
                    "last_name": "Poulopoulos",
                    "company_name": "Dimpo"}
        location:
          type: object
          example: {"latitude": "-122.290883",
                    "id": 30,
                    "creation_time": "2020-08-15T10:37:06",
                    "person_id": 5,
                    "longitude": "37.55363"}